# SPDX-FileCopyrightText: 2024 Howetuft
#
# SPDX-License-Identifier: Apache-2.0

# TODO Add AUTHORS

[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "pyluxcore"
version = "2.9.alpha1"
wheel.py-api = "py3"

[tool.scikit-build]
cmake.verbose = true
logging.level = "INFO"
cmake.source-dir = "./LuxCore"
wheel.cmake = true

[tool.scikit-build.cmake.define]
OpenGL_GL_PREFERENCE= "LEGACY"

[[tool.scikit-build.overrides]]
if.platform-system = "linux"
cmake.args = ["-DLUXRAYS_CUSTOM_CONFIG=Config_Linux-Static", "-DPYTHON_V=3", "-DEMBREE_SEARCH_PATH=/usr/lib64", "-DCMAKE_C_COMPILER_LAUNCHER=sccache", "-DCMAKE_CXX_COMPILER_LAUNCHER=sccache"]

[tool.cibuildwheel]
build-frontend = "build"
build-verbosity = 3
build = "cp38-*"  # TODO
manylinux-x86_64-image = "manylinux_2_28"

[tool.cibuildwheel.linux]
before-all = "source /project/scripts/before_all_linux.sh"
