# SPDX-FileCopyrightText: 2024 Howetuft
#
# SPDX-License-Identifier: Apache-2.0

name: linux-clean-tree
description: LuxCore Python Wheels - Clean/update source tree for Linux build
runs:
  using: 'composite'
  steps:

    - name: Add missing include in OCIO dep
      shell: 'bash'
      working-directory: ${{ github.workspace }}/LuxCore
      run: |
        sed -i "8i #include<cstring>" deps/opencolorio-2.0.0/src/OpenColorIO/FileRules.cpp

    - name: Fix libOpenImageDenoise version
      shell: 'bash'
      working-directory: ${{ github.workspace }}/LuxCore
      run: |
        sed -i "s/libOpenImageDenoise.so.0/libOpenImageDenoise.so.1/g" \
          cmake/Packages/FindOidn.cmake
