# SPDX-FileCopyrightText: 2024 Howetuft
#
# SPDX-License-Identifier: Apache-2.0

name: windows-python-deps
description: LuxCore Python Wheels - Prepare Python dependencies for Windows build
inputs:
  job-id:
    description: 'Job unique identifier (for caching)'
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: Export cache information
      uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Restore pip cache
      uses: actions/cache/restore@v4
      id: cache-pip-restore
      with:
        path: 'c:\users\runneradmin\appdata\local\pip\cache'
        key: ${{ inputs.job-id }}-pip-${{ hashFiles('requirements.txt') }}

    - name: Update Python dependencies
      id: pip-update
      run: |
        python -m pip cache dir
        python -m pip install -r requirements.txt
        echo "Cache hit: ${{steps.cache-pip-restore.outputs.cache-hit}}"
      shell: bash

    - name: Save pip cache
      id: cache-pip-save
      uses: actions/cache/save@v4
      if: steps.cache-pip-restore.outputs.cache-hit != 'true'
      with:
        path: 'c:\users\runneradmin\appdata\local\pip\cache'
        key: ${{ steps.cache-pip-restore.outputs.cache-primary-key }}
