# SPDX-FileCopyrightText: 2025 Howetuft
#
#
# SPDX-License-Identifier: Apache-2.0


# Check that dependencies are suitable for future use


name: LuxCore Dependency Checker

on:
  workflow_dispatch:
  push:

jobs:
  call-build-deps:
    uses: ./.github/workflows/build.yml

  check-deps:
    name: Check dependencies
    runs-on: ${{ matrix.os }}
    needs: [call-build-deps]
    strategy:
      fail-fast: True
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
    steps:
      - name: Checkout LuxCore repository
        uses: actions/checkout@v4
        with:
          repository: 'LuxCoreRender/LuxCore'
          ref: 'for_v2.10'

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: luxcore-deps-${{ matrix.os }}
          path: ${{ github.workspace }}/dist
          merge-multiple: false

      - name: Display structure of downloaded files
        shell: bash
        run: ls -R $GITHUB_WORKSPACE/dist

      - name: Install Conan
        run: pip install conan

      - name: Prepare deps
        shell: bash
        run: |
          _path=${{ github.workspace }}/dist/luxcore-deps-${{ matrix.os }}
          python cmake/make_deps.py -l ${_path}/conan-cache-save.tgz -v

      - name: Build LuxCore
        run: make
