# SPDX-FileCopyrightText: 2024 Howetuft
#
# SPDX-License-Identifier: Apache-2.0

name: LuxCore Python wheels

on: [push, pull_request]

#permissions:
#  id-token: write # Important for at least docker gha cache
#  contents: write

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #python-minor: ['8', '9', '10', '11', '12']
        python-minor: ['12']
        # os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        os: [windows-latest]
    env:
      GH_TOKEN: ${{ github.token }}
      SCCACHE_GHA_ENABLED: on
      SCCACHE_DIRECT: on
      CMAKE_MESSAGE_LOG_LEVEL: VERBOSE

    steps:

      - name: Checkout repository and submodule(s)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.${{ matrix.python-minor }}'

      - name: Windows - Prepare Python deps
        if: ${{ runner.os }} == "Windows"
        uses: ./.github/actions/windows-python-deps
        with:
          job-id: ${{ matrix.os }}-${{ matrix.python-minor }}

      - name: Windows - Set up build system
        if: ${{ runner.os }} == "Windows"
        uses: ./.github/actions/windows-build-system
        with:
          job-id: ${{ matrix.os }}-${{ matrix.python-minor }}

      - name: Windows - Clean source tree
        if: ${{ runner.os }} == "Windows"
        uses: ./.github/actions/windows-clean-tree

      # - name: Windows - Build boost-python and boost-numpy
      #   if: ${{ runner.os }} == "Windows"
      #   uses: ./.github/actions/windows-boost-python
      #   with:
      #     job-id: ${{ matrix.os }}-${{ matrix.python-minor }}


      # - name: Windows - Build oidn
      #   if: ${{ runner.os }} == "Windows"
      #   uses: ./.github/actions/windows-oidn
      #   with:
      #     job-id: ${{ matrix.os }}-${{ matrix.python-minor }}

      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3



      # Build wheel
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.1
        env:
          SCCACHE_GHA_ENABLED: "true"
          CIBW_BUILD_FRONTEND: build
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: cp3${{ matrix.python-minor }}-*
          CIBW_SKIP: "*musllinux*"
          CIBW_ARCHS: auto64
          CIBW_ENVIRONMENT_PASS_LINUX: |
            SCCACHE_GHA_ENABLED
            SCCACHE_DIRECT
            ACTIONS_CACHE_URL
            ACTIONS_RUNTIME_TOKEN
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_BEFORE_ALL_LINUX: source /project/scripts/before_all_linux.sh
          CIBW_BEFORE_BUILD_WINDOWS: bash.exe %GITHUB_WORKSPACE%/scripts/before_build_windows.sh
          CIBW_ENVIRONMENT_WINDOWS: >-
            SCCACHE_C_CUSTOM_CACHE_BUSTER='3.${{ matrix.python-minor }}'
            SCCACHE_LOG=debug
            LIBDIR='${{ env.Python_ROOT_DIR }}'
            SKBUILD_CMAKE_ARGS='--preset=conan-release;-G Ninja;--log-level=VERBOSE'
            PYTHON_V=''
            SPDLOG_FMT_EXTERNAL=on
            #CMAKE_LIBRARY_PATH='${{ env.PYTHONLOCATION }}\libs'
            #CMAKE_INCLUDE_PATH='${{ env.WINDOWS_DEPS }}\include'
            #CMAKE_PREFIX_PATH='${{ env.WINDOWS_DEPS }}'
            #BOOST_ROOT='${{ steps.boost.outputs.root }}'
            #BOOST_LIBRARYDIR='${{ steps.boost.outputs.librarydir }}'
            #CMAKE_BUILD_TYPE='Release'
            #CMAKE_BUILD_PARALLEL_LEVEL='4'
            #CXXFLAGS='-DBOOST_NO_CXX11_SCOPED_ENUMS -DBOOST_FILESYSTEM_VERSION=3'
            #CFLAGS='-DXML_STATIC'
            #CMAKE_CXX_COMPILER_LAUNCHER=sccache
            #CMAKE_C_COMPILER_LAUNCHER=sccache
            #CMAKE_CXX_STANDARD=17
            #CMAKE_BUILD_TYPE='Release'
        with:
            package-dir: .
            output-dir: wheelhouse
            config-file: "{package}/pyproject.toml"


      #- name: Setup tmate session
        #if: ${{ failure() }}
        #uses: mxschmitt/action-tmate@v3

      ## Upload sccache log (debug)
      #- uses: actions/upload-artifact@v4
        #if: always()
        #with:
          #name: sccache_${{ matrix.python-minor }}
          #path: 'C:\hostedtoolcache\windows\sccache\sccache.log'


      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
